name: gan-shmuel-production

include:
  - ../billing/compose.yaml
  - ../weight/compose.yaml

networks:
  gan_shmuel_shared:
    external: true
    name: ${SHARED_NETWORK_NAME:-gan_shmuel_prod_shared}