name: gan-shmuel-integration

include:
  - ../billing/compose.yaml
  - ../weight/compose.yaml

networks:
  gan_shmuel_shared:
    external: true

services:
  front-app:
    build:
      context: ../front
      dockerfile: Dockerfile
    ports:
      - "8089:80"
    networks:
      - gan_shmuel_shared
    depends_on:
      billing-app:
        condition: service_started
      weight-app:
        condition: service_started

  healthcheck:
    image: busybox
    depends_on:
      billing-app:
        condition: service_started
      weight-app:
        condition: service_started
    networks:
      - gan_shmuel_shared
    command: sh -c "echo 'Integration successful'"
