# Use the lightweight Alpine-based Nginx image
FROM nginx:alpine

# Copy the static website files to Nginx's default public directory
COPY . /usr/share/nginx/html

# Expose port 80 for traffic
EXPOSE 8089
